name: NewsApp_Chingu
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.2.0+1
  flutter_web_browser: ^0.11.0
  share: ^0.6.4+3
  fluttericon: ^1.0.7
  modal_progress_hud: ^0.1.3
  hive_flutter: ^0.3.1
  hive: ^1.4.3
  path_provider: ^1.6.11
  dio: ^3.0.10
  cupertino_icons: ^0.1.3
  auto_route: ^0.6.7
  stacked: ^1.7.6
  connectivity_wrapper: ^1.0.4
  flutter_dotenv: ^2.1.0
  get_it: ^5.0.0
  # device_preview: ^0.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: null
  auto_route_generator: null
dependency_overrides:
  analyzer: '0.39.14'

flutter:

  uses-material-design: true

  assets:
    - assets/
    - myApiKey.env

